#!/usr/bin/python3
import requests
import json
import pandas as pd
import math
from datetime import datetime

stock_url = 'https://etmarketsapis.indiatimes.com/ET_Stats/recoveryfromlow?pageno=1&pagesize=50&sortby=aboveDaysLowPerChange&sortorder=desc&service=intradaylow&exchange=nse&marketcap=largecap%2Cmidcap'

headers = {
     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'}
response = requests.get(stock_url, headers=headers)

#Symbol= "BANKNIFTY"
#new_url = 'https://www.nseindia.com/api/option-chain-indices?symbol='+ Symbol
#headers = headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'}
#page = requests.get(new_url,headers=headers)
dajs = json.loads(response.text)

print(dajs)
