#!/usr/bin/python3
import requests
import json
import pandas as pd
import math
from datetime import datetime
import sys

data=sys.argv[1]
stock_url = 'https://www1.nseindia.com/live_market/dynaContent/live_watch/stock_watch/'+data

headers = {
     'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'}
response = requests.get(stock_url, headers=headers)

#Symbol= "BANKNIFTY"
#new_url = 'https://www.nseindia.com/api/option-chain-indices?symbol='+ Symbol
#headers = headers = {'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36'}
#page = requests.get(new_url,headers=headers)
dajs = json.loads(response.text)

print(dajs)
